version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID: "905418199722"
    ECR_REPO_NAME: "marketplace"
    ECR_IMAGE_TAG: "latest"
    COMMIT_ID: ""

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version
      - echo "Installing npm version compatible with Node.js 16.20.2 ..."
      - npm install -g npm@8.19.4
      - npm install @types/node@latest --save-dev --force

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG . --progress plain
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID

services:
  barinb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOOGLE_MAPS_KEY: ''
    restart: 'no'
    ports:
      - 4000:80
    volumes:
      - ./src:/var/www/html
      
