version: '3.3'

services:
  barinb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOOGLE_MAPS_KEY: ''
    restart: 'no'
    ports:
      - 4000:80
    volumes:
      - ./src:/var/www/html

